### ISSUE TITLE
Calling Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by rmetzler** [aisipos/homebrew-libgnomeui#2]
```
$ brew -v
Homebrew 0.9.9 (git revision 9fd97; last commit 2016-09-03)
Homebrew/homebrew-core (git revision 4025; last commit 2016-09-03)
```

when I run `$ brew outdated` I get the deprecation warnings below. Here is a Github issue explaining these: https://github.com/Homebrew/brew/issues/606

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-mime-data.rb:6:in `<class:GnomeMimeData>'
Please report this to the aisipos/libgnomeui tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-mime-data.rb:6:in `<class:GnomeMimeData>'
Please report this to the aisipos/libgnomeui tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-mime-data.rb:6:in `<class:GnomeMimeData>'
Please report this to the aisipos/libgnomeui tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-vfs.rb:6:in `<class:GnomeVfs>'
Please report this to the aisipos/libgnomeui tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-vfs.rb:6:in `<class:GnomeVfs>'
Please report this to the aisipos/libgnomeui tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/aisipos/homebrew-libgnomeui/gnome-vfs.rb:6:in `<class:GnomeVfs>'
Please report this to the aisipos/libgnomeui tap!
```

**Comment by coox** [comment]
SHA1 formula checksums are now disabled in Homebrew.

```
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
```

I have submitted a [pull request](https://github.com/aisipos/homebrew-libgnomeui/pull/3) on the matter, but I'm not sure whether it will be merged, or if this repository should be considered unmaintained.

**Comment by aisipos** [comment]
@rmetzler Thank you for the report, and @coox thank you for the fix. I apologize for the very long delay in merging. 

As of now, I had to manually
`brew install homebrew/dupes/libiconv`

then I need to twice:
`brew install aisipos/libgnomeui/etherape` 

And once installed, I still need to do the 
`DYLD_FALLBACK_LIBRARY_PATH=$(brew --prefix)/lib/libglade/2.0/ etherape`
to run.

Despite all those caveats, etherape actually runs afterwards. Thanks again for the help.
