### ISSUE TITLE
Error: uninitialized constant #<Class:0x007f899f10c220>::DATA -- macOS 10.13.4

### ISSUE THREAD

**Issue by srooke999** [aisipos/homebrew-libgnomeui#5]
Running macOS 10.13.4, Xcode 9.3 (9E145) on a 12-core MacPro (late 2013).
Reporting here after reading instructions about Taps on docs.brew.sh/Troubleshooting.

$ brew install libbonoboui
==> Installing libbonoboui from aisipos/libgnomeui
==> Installing dependencies for aisipos/libgnomeui/libbonoboui: libbonobo, gnome-vfs, libtool, libogg, libvorbis, libcanberra, libgnome
==> Installing aisipos/libgnomeui/libbonoboui dependency: libbonobo
==> Downloading http://ftp.gnome.org/pub/GNOME/sources/libbonobo/2.32/libbonobo-2.32.1.tar.gz
Already downloaded: /Users/rooke/Library/Caches/Homebrew/libbonobo-2.32.1.tar.gz
Error: uninitialized constant #<Class:0x007ff8ecb807f8>::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/aisipos/homebrew-libgnomeui/libbonobo.rb:20:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1904:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

**Comment by vanzandtj** [comment]
My system:
MacBook Pro (Retina, 13-inch, Early 2015)
macOS High Sierra, Version 10.13.4
Xcode 9.3

I am trying to build inkscape, and ran into a similar problem installing gnome-vfs:

$ brew install gnome-vfs
==> Installing gnome-vfs from aisipos/libgnomeui
==> Downloading http://ftp.gnome.org/pub/gnome/sources/gnome-vfs/2.24/gnome-vfs-2.24.4.tar.gz
Already downloaded: /Users/jrv/Library/Caches/Homebrew/gnome-vfs-2.24.4.tar.gz
Error: uninitialized constant #<Class:0x000001011da130>::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/aisipos/homebrew-libgnomeui/gnome-vfs.rb:10:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1904:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

**Comment by Chengcheng-Xiao** [comment]
Same here. 
By commenting out "DATA" in Taps/aisipos/homebrew-libgnomeui/gnome-vfs.rb, the configure process can proceed as expected.
However, Because some deprecated glib2 functionality, compilation still got stuck.
I have find a patch file at [link](https://trac.macports.org/attachment/ticket/38657/patch-port-glib2-2.6.31-and-up.diff).
I don't know much about homebrew rather than use it (sadly). May be the owner could fix this issue.
